# Generated by Django 3.0.3 on 2020-03-03 18:37

import collaborators.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=collaborators.models.MetadataOptions)),
            ],
        ),
    ]
