# Generated by Django 3.0.3 on 2020-03-03 19:22

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collaborator',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
