# Generated by Django 3.0.3 on 2020-02-23 01:11

import collaborators.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_auto_20200221_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=collaborators.models.MetadataOptions),
        ),
    ]
