# Generated by Django 3.0.3 on 2020-03-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0003_auto_20200223_0111'),
        ('collaborators', '0002_auto_20200303_1922'),
    ]

    operations = [
    ]
