# Generated by Django 3.0.3 on 2020-02-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=128)),
                ('repo_name', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('repo_owner', 'repo_name')},
            },
        ),
    ]
