# Generated by Django 3.0.3 on 2020-02-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200220_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='authors',
            new_name='collaborators',
        ),
    ]
