# Generated by Django 3.0.3 on 2020-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_auto_20200221_1547'),
        ('projects', '0003_auto_20200221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='collaborators.Collaborator'),
        ),
    ]
