# Generated by Django 3.0.3 on 2020-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200222_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_owner',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
