name: Hello World
# Triggers on push or pull request
on: [push, pull_request]

jobs:
  echo:
    name: HelloWorld
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello-world
        run: |
          echo "Hello World"
