name: upload-history

on: [pull_request]

jobs:
  build:
    - name: Run Git Chaos
      uses: chaos-monkeys/git-chaos-action
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.ACTIONS_AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.ACTIONS_AWS_SECRET_KEY }}
